version: "3.8"
services:
  companies-db:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: companies
      POSTGRES_USER: companies
      POSTGRES_DB: companies
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata